"""
Tests for the auxiliary operator scripts: crosscheck.py + build_manual.py.

We use the autouse `isolated_config` fixture from conftest.py to point
LOVEWORK_WIKI / LOVEWORK_CACHE at a temp dir. The cross-check tests
seed applications/ with a fake case so the prior-contact branch fires.
"""

import json
import re
from datetime import date, timedelta
from pathlib import Path

import pytest

import build_manual
import config
import crosscheck
from job_registry import JobRegistry


# ── crosscheck.py ────────────────────────────────────────────────────────

SAMPLE_REPORT = """# FULL SWEEP — 2026-06-20 11:25:54 BST

Profile: LJ-general

Generated by lovework-agent. Total findings: 224

**Decisions:** GO: 19 · MAYBE: 48 · FLAG: 44 · DROP: 113
**Lifecycle:** New: 224 · Still open: 0 · Long-lasting: 0

---

## New Listings (224)

### Poolside — Member of Engineering (Pre-training / Data Acquisition)

- **URL**: https://poolside.ai/careers/example
- **Location**: Remote
- **Score**: 8.5/10
- **Reasoning**: strong fit.

### Aleph Alpha — Senior AI Researcher

- **URL**: https://jobs.ashbyhq.com/AlephAlpha/example
- **Score**: 8.5/10
- **Reasoning**: good fit.

### NoCo — Engineer

- **URL**: https://noco.example/jobs/1
- **Score**: 9.0/10
- **Reasoning**: perfect.

### OldOrg — VP of Sales

- **Score**: 9.0/10
- **Decision**: DROP
- **Reasoning**: no fit.

## DROP (1)
"""


def test_parse_report_extracts_go_sections(tmp_path):
    report = tmp_path / "2026-06-20-lj-general-report.md"
    report.write_text(SAMPLE_REPORT, encoding="utf-8")
    listings = crosscheck.parse_report(report, include_maybe=False)
    # 3 GOs (the DROP is skipped), but only 2 with URL + score; the 3rd has
    # only a score line. All 3 should be parsed.
    orgs = [l["org"] for l in listings]
    assert "Poolside" in orgs
    assert "Aleph Alpha" in orgs
    assert "NoCo" in orgs
    assert "OldOrg" not in orgs  # explicit DROP, not in GO section


def test_parse_report_includes_maybe_when_flagged(tmp_path):
    report = tmp_path / "r.md"
    report.write_text(SAMPLE_REPORT, encoding="utf-8")
    only_go = crosscheck.parse_report(report, include_maybe=False)
    with_maybe = crosscheck.parse_report(report, include_maybe=True)
    # The report has only GO + DROP sections, so the flag shouldn't change anything.
    # (include_maybe only matters when there's a ## MAYBE section.)
    assert len(only_go) == len(with_maybe)


def test_parse_report_index_format(tmp_path):
    """Index-format listings: '- **DATE** | Org — Title | SCORE/10 [url](url)'."""
    text = """\
# LoveWork Index

- **2026-06-20** | Poolside — Member of Engineering (Pre-training) | 8.5/10 [https://poolside.ai/x](https://poolside.ai/x)
- **2026-06-20** | Aleph Alpha — Senior AI Researcher | 7.0/10 [https://aleph.example/j](https://aleph.example/j)
"""
    report = tmp_path / "index.md"
    report.write_text(text, encoding="utf-8")
    listings = crosscheck.parse_report(report)
    assert len(listings) == 2
    assert listings[0]["org"] == "Poolside"
    assert listings[0]["score"] == 8.5
    assert "poolside.ai" in listings[0]["url"]


def test_crosscheck_finds_prior_contact(tmp_path, monkeypatch):
    """A fake applications/ with a Poolside rejection triggers a cross-check."""
    # Seed the wiki with the report in a temp dir, NOT the real one.
    fake_reports = tmp_path / "reports"
    fake_reports.mkdir()
    (fake_reports / "2026-06-20-lj-general-report.md").write_text(SAMPLE_REPORT, encoding="utf-8")
    monkeypatch.setattr(config, "WIKI_REPORTS", fake_reports)
    monkeypatch.setattr(config, "WIKI_ORGS", tmp_path / "orgs")
    monkeypatch.setattr(config, "WIKI_ROOT", tmp_path / "wiki")

    # Seed the applications dir with a fake prior application that includes
    # a rejection marker. Use a unique org name to avoid conflicts with
    # any pre-existing real data.
    org_name = "TestCo"
    app_dir = config.APPLICATIONS_DIR / f"20260419-{org_name}-Some_Role"
    if app_dir.exists():
        import shutil
        shutil.rmtree(app_dir)
    app_dir.mkdir(parents=True)
    txt = app_dir / f"20260419-{org_name}-Some_Role.txt"
    txt.write_text(
        "Applied.\n\nRejection received 2026-05-01: decided not to move forward.",
        encoding="utf-8",
    )

    # Import the actual PriorContact / PriorApplication from history.
    from history import PriorContact, PriorApplication

    # Stub Gmail so we don't depend on google_api.py.
    monkeypatch.setattr(crosscheck, "scan_history", lambda org, use_gmail: (
        PriorContact(
            org=org_name,
            applications=[PriorApplication(
                date="2026-04-19", company=org_name, role="Some Role",
                path=app_dir, txt_path=txt, has_rejection=True, rejection_date="2026-05-01",
            )],
            gmail_events=[],
        ) if org == org_name else PriorContact(org=org)
    ))

    found = crosscheck.cross_check(
        org_name, "Member of Engineering (Pre-training / Data Acquisition)",
        8.5, "https://testco.example/x", today="2026-06-23", wiki=None,
    )
    assert found is not None
    assert found["has_rejection"] is True
    assert "rejection" in found["summary"].lower()
    assert "Some Role" in found["summary"]


# ── build_manual.py ──────────────────────────────────────────────────────

SAMPLE_REPORT_FOR_MANUAL = SAMPLE_REPORT


def test_extract_top_gos_picks_highest_scores(tmp_path):
    report = tmp_path / "r.md"
    report.write_text(SAMPLE_REPORT_FOR_MANUAL, encoding="utf-8")
    gos = build_manual._extract_top_gos(report, n=2)
    # Highest score: 9.0 (NoCo, from ## New Listings), then 8.5 (Poolside/Aleph).
    # _extract_top_gos picks GOs by default, so entries in "## New Listings"
    # are treated as GO (the wiki writer only renders GO + MAYBE in that
    # section). NoCo is 9.0, Poolside + Aleph Alpha are 8.5 — top 2 by
    # score should be NoCo + either Poolside or Aleph.
    assert len(gos) == 2
    assert gos[0]["org"] == "NoCo"
    assert gos[0]["score"] == 9.0
    # Second must be 8.5.
    assert gos[1]["score"] == 8.5


def test_extract_top_gos_handles_inline_decision(tmp_path):
    """Newer report format embeds the decision in the score line."""
    text = """\
# INCREMENTAL — 2026-06-23 16:16:33 BST

### Poolside — Member of Engineering (Pre-training / Data Acquisition)

- **Score**: 8.5/10 (GO)
- **URL**: https://poolside.ai/x
- **Location**: Remote

### NoCo — Engineer

- **Score**: 9.0/10 (GO)
- **URL**: https://noco.example/1
"""
    report = tmp_path / "r.md"
    report.write_text(text, encoding="utf-8")
    gos = build_manual._extract_top_gos(report, n=5)
    assert len(gos) == 2
    assert all(g["decision"] == "GO" for g in gos)
    # Sorted by score desc.
    assert gos[0]["org"] == "NoCo"


def test_read_report_header_handles_standard_format(tmp_path):
    report = tmp_path / "r.md"
    report.write_text(SAMPLE_REPORT, encoding="utf-8")
    h = build_manual._read_report_header(report)
    assert h.get("date") == "2026-06-20"
    assert h.get("profile") == "LJ-general"
    assert h.get("GO") == 19
    assert h.get("MAYBE") == 48
    assert h.get("new") == 224


def test_read_report_header_handles_incremental_format(tmp_path):
    text = """\
# INCREMENTAL — 2026-06-23 16:16:33 BST

Generated by lovework-agent.
"""
    report = tmp_path / "r.md"
    report.write_text(text, encoding="utf-8")
    h = build_manual._read_report_header(report)
    assert h.get("date") == "2026-06-23"
    assert h.get("profile") == "incremental"


def test_read_report_header_falls_back_to_counting_decisions(tmp_path):
    """When the summary line is missing, count ### sections with (GO) etc."""
    text = """\
# INCREMENTAL — 2026-06-23 16:16:33 BST

### A — x

- **Score**: 8.0/10 (GO)

### B — y

- **Score**: 7.0/10 (MAYBE)
"""
    report = tmp_path / "r.md"
    report.write_text(text, encoding="utf-8")
    h = build_manual._read_report_header(report)
    assert h.get("GO") == 1
    assert h.get("MAYBE") == 1


def test_run_log_returns_newest_first(tmp_path):
    (tmp_path / "2026-06-20-r.md").write_text(SAMPLE_REPORT, encoding="utf-8")
    (tmp_path / "2026-06-23-r.md").write_text(SAMPLE_REPORT, encoding="utf-8")
    # Inject into config so _run_log uses tmp_path.
    import unittest.mock as um
    with um.patch.object(config, "WIKI_REPORTS", tmp_path):
        log = build_manual._run_log(limit=5)
    assert len(log) == 2
    # Newest first.
    assert log[0]["file"] == "2026-06-23-r.md"
    assert log[1]["file"] == "2026-06-20-r.md"


def test_build_manual_writes_to_lovework_root(tmp_path, monkeypatch):
    """End-to-end: build_manual.main writes MANUAL.md to LOVEWORK_ROOT."""
    # Use the isolated config from conftest; override LOVEWORK_ROOT to a temp.
    fake_root = tmp_path / "lovework"
    fake_root.mkdir()
    (fake_root / "wiki").mkdir()
    (fake_root / "wiki" / "reports").mkdir()
    (fake_root / "wiki" / "orgs").mkdir()
    cache = tmp_path / "cache"
    cache.mkdir(exist_ok=True)
    # Plant a report and a registry so the manual has content.
    (fake_root / "wiki" / "reports" / "2026-06-23-r.md").write_text(SAMPLE_REPORT, encoding="utf-8")
    monkeypatch.setattr(config, "LOVEWORK_ROOT", fake_root)
    monkeypatch.setattr(config, "WIKI_ROOT", fake_root / "wiki")
    monkeypatch.setattr(config, "WIKI_REPORTS", fake_root / "wiki" / "reports")
    monkeypatch.setattr(config, "WIKI_ORGS", fake_root / "wiki" / "orgs")
    monkeypatch.setattr(config, "CACHE_DIR", cache)

    build_manual.main()
    manual = fake_root / "MANUAL.md"
    assert manual.exists()
    text = manual.read_text(encoding="utf-8")
    assert "LoveWork — Operator's Manual" in text
    assert "Refresh now" in text
    assert "Poolside" in text
